import { FeedItem, Folder } from './types';

export const MOCK_FOLDERS: Folder[] = [
  { id: 'all', name: 'All Feeds', icon: 'LayoutGrid' },
  { id: 'saved', name: 'Saved Items', icon: 'Bookmark' },
  { id: 'tech', name: 'Tech', icon: 'Cpu' },
  { id: 'humor', name: 'Humor', icon: 'Laugh' },
  { id: 'podcasts', name: 'Podcasts', icon: 'Mic' },
  { id: 'design', name: 'Design', icon: 'Palette' },
];

export const MOCK_FEED: FeedItem[] = [
  {
    id: '1',
    type: 'article',
    source: 'The Verge',
    sourceIcon: 'https://www.google.com/s2/favicons?domain=theverge.com&sz=32',
    title: 'The Future of AI is Multimodal',
    description: 'How the next generation of large language models will understand images, audio, and video as well as text.',
    timestamp: Date.now() - 7200000,
    thumbnail: 'https://picsum.photos/seed/verge/400/400',
    link: 'https://www.theverge.com',
    pubDate: new Date().toISOString(),
  },
  {
    id: '2',
    type: 'video',
    source: 'MKBHD',
    sourceIcon: 'https://www.google.com/s2/favicons?domain=youtube.com&sz=32',
    title: 'The Apple Vision Pro Review: 6 Months Later',
    timestamp: Date.now() - 18000000,
    thumbnail: 'https://picsum.photos/seed/mkbhd/1280/720',
    duration: '18:42',
    link: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    pubDate: new Date().toISOString(),
  },
  {
    id: '3',
    type: 'podcast',
    source: 'Lex Fridman Podcast',
    sourceIcon: 'https://www.google.com/s2/favicons?domain=lexfridman.com&sz=32',
    title: 'Sam Altman: OpenAI and the Future of AGI',
    timestamp: Date.now() - 86400000,
    thumbnail: 'https://picsum.photos/seed/lex/300/300',
    duration: '2:45:12',
    link: 'https://lexfridman.com',
    pubDate: new Date().toISOString(),
  },
  {
    id: '4',
    type: 'reddit',
    source: 'r/technology',
    author: 'u/tech_enthusiast',
    title: 'New battery technology could double EV range by 2026',
    timestamp: Date.now() - 10800000,
    thumbnail: 'https://picsum.photos/seed/reddit/600/400',
    votes: '4.2k',
    comments: 842,
    link: 'https://reddit.com',
    pubDate: new Date().toISOString(),
    content: 'Discussion about the new solid-state battery breakthroughs...'
  },
  {
    id: '5',
    type: 'article',
    source: 'TechCrunch',
    sourceIcon: 'https://www.google.com/s2/favicons?domain=techcrunch.com&sz=32',
    title: 'Startup raises $50M for sustainable fashion',
    description: 'A new platform aims to make the fashion industry more transparent and eco-friendly.',
    timestamp: Date.now() - 21600000,
    thumbnail: 'https://picsum.photos/seed/tc/400/400',
    link: 'https://techcrunch.com',
    pubDate: new Date().toISOString(),
  },
  {
    id: '6',
    type: 'video',
    source: 'Veritasium',
    sourceIcon: 'https://www.google.com/s2/favicons?domain=youtube.com&sz=32',
    title: 'The Most Misunderstood Concept in Physics',
    timestamp: Date.now() - 43200000,
    thumbnail: 'https://picsum.photos/seed/physics/1280/720',
    duration: '12:04',
    link: 'https://youtube.com',
    pubDate: new Date().toISOString(),
  }
];
